# Generated by Django 4.0.1 on 2022-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=40)),
            ],
        ),
    ]
